// ThinkingLanguage — Bytecode chunk (compiled function)

use std::sync::Arc;
use tl_ast::Expr as AstExpr;

/// A compiled function / top-level script.
#[derive(Debug, Clone)]
pub struct Prototype {
    /// Bytecode instructions
    pub code: Vec<u32>,
    /// Constant pool
    pub constants: Vec<Constant>,
    /// Source line for each instruction (for error reporting)
    pub lines: Vec<u32>,
    /// Number of parameters
    pub arity: u8,
    /// Number of local variable slots needed
    pub num_locals: u8,
    /// Number of registers needed
    pub num_registers: u8,
    /// Upvalue definitions (how to capture from enclosing scope)
    pub upvalue_defs: Vec<UpvalueDef>,
    /// Function name (for debugging)
    pub name: String,
    /// Whether this function contains yield (is a generator)
    pub is_generator: bool,
}

impl Prototype {
    pub fn new(name: String) -> Self {
        Prototype {
            code: Vec::new(),
            constants: Vec::new(),
            lines: Vec::new(),
            arity: 0,
            num_locals: 0,
            num_registers: 0,
            upvalue_defs: Vec::new(),
            name,
            is_generator: false,
        }
    }
}

/// Constant pool entry.
#[derive(Debug, Clone)]
pub enum Constant {
    Int(i64),
    Float(f64),
    String(Arc<str>),
    /// A nested function prototype
    Prototype(Arc<Prototype>),
    /// Raw AST expression — used for table pipe operations
    /// so the VM can pass it to translate_expr at runtime
    AstExpr(Box<AstExpr>),
    /// A list of AST expressions (for table op args)
    AstExprList(Vec<AstExpr>),
}

/// How to capture an upvalue from the enclosing function.
#[derive(Debug, Clone, Copy)]
pub struct UpvalueDef {
    /// If true, capture from enclosing function's locals.
    /// If false, capture from enclosing function's upvalues.
    pub is_local: bool,
    /// Index into enclosing function's locals or upvalues.
    pub index: u8,
}

/// Builtin function identifiers — avoids string comparisons in the VM hot loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum BuiltinId {
    Print = 0,
    Println = 1,
    Len = 2,
    Str = 3,
    Int = 4,
    Float = 5,
    Abs = 6,
    Min = 7,
    Max = 8,
    Range = 9,
    Push = 10,
    TypeOf = 11,
    Map = 12,
    Filter = 13,
    Reduce = 14,
    Sum = 15,
    Any = 16,
    All = 17,
    ReadCsv = 18,
    ReadParquet = 19,
    WriteCsv = 20,
    WriteParquet = 21,
    Collect = 22,
    Show = 23,
    Describe = 24,
    Head = 25,
    Postgres = 26,
    // AI builtins
    Tensor = 27,
    TensorZeros = 28,
    TensorOnes = 29,
    TensorShape = 30,
    TensorReshape = 31,
    TensorTranspose = 32,
    TensorSum = 33,
    TensorMean = 34,
    TensorDot = 35,
    Predict = 36,
    Similarity = 37,
    AiComplete = 38,
    AiChat = 39,
    ModelSave = 40,
    ModelLoad = 41,
    ModelRegister = 42,
    ModelList = 43,
    ModelGet = 44,
    // Streaming builtins
    AlertSlack = 45,
    AlertWebhook = 46,
    Emit = 47,
    Lineage = 48,
    RunPipeline = 49,
    // Phase 5: Math builtins
    Sqrt = 50,
    Pow = 51,
    Floor = 52,
    Ceil = 53,
    Round = 54,
    Sin = 55,
    Cos = 56,
    Tan = 57,
    Log = 58,
    Log2 = 59,
    Log10 = 60,
    Join = 61,
    // Phase 5: HTTP builtins
    HttpGet = 62,
    HttpPost = 63,
    // Phase 5: Assert builtins
    Assert = 64,
    AssertEq = 65,
    // Phase 6: Stdlib & Ecosystem
    JsonParse = 66,
    JsonStringify = 67,
    MapFrom = 68,
    ReadFile = 69,
    WriteFile = 70,
    AppendFile = 71,
    FileExists = 72,
    ListDir = 73,
    EnvGet = 74,
    EnvSet = 75,
    RegexMatch = 76,
    RegexFind = 77,
    RegexReplace = 78,
    Now = 79,
    DateFormat = 80,
    DateParse = 81,
    Zip = 82,
    Enumerate = 83,
    Bool = 84,
    // Phase 7: Concurrency
    Spawn = 85,
    Sleep = 86,
    Channel = 87,
    Send = 88,
    Recv = 89,
    TryRecv = 90,
    AwaitAll = 91,
    Pmap = 92,
    Timeout = 93,
    // Phase 8: Iterators & Generators
    Next = 94,
    IsGenerator = 95,
    Iter = 96,
    Take = 97,
    Skip_ = 98,
    GenCollect = 99,
    GenMap = 100,
    GenFilter = 101,
    Chain = 102,
    GenZip = 103,
    GenEnumerate = 104,
}

impl BuiltinId {
    pub fn from_name(name: &str) -> Option<BuiltinId> {
        match name {
            "print" => Some(BuiltinId::Print),
            "println" => Some(BuiltinId::Println),
            "len" => Some(BuiltinId::Len),
            "str" => Some(BuiltinId::Str),
            "int" => Some(BuiltinId::Int),
            "float" => Some(BuiltinId::Float),
            "abs" => Some(BuiltinId::Abs),
            "min" => Some(BuiltinId::Min),
            "max" => Some(BuiltinId::Max),
            "range" => Some(BuiltinId::Range),
            "push" => Some(BuiltinId::Push),
            "type_of" => Some(BuiltinId::TypeOf),
            "map" => Some(BuiltinId::Map),
            "filter" => Some(BuiltinId::Filter),
            "reduce" => Some(BuiltinId::Reduce),
            "sum" => Some(BuiltinId::Sum),
            "any" => Some(BuiltinId::Any),
            "all" => Some(BuiltinId::All),
            "read_csv" => Some(BuiltinId::ReadCsv),
            "read_parquet" => Some(BuiltinId::ReadParquet),
            "write_csv" => Some(BuiltinId::WriteCsv),
            "write_parquet" => Some(BuiltinId::WriteParquet),
            "collect" => Some(BuiltinId::Collect),
            "show" => Some(BuiltinId::Show),
            "describe" => Some(BuiltinId::Describe),
            "head" => Some(BuiltinId::Head),
            "postgres" => Some(BuiltinId::Postgres),
            "tensor" => Some(BuiltinId::Tensor),
            "tensor_zeros" => Some(BuiltinId::TensorZeros),
            "tensor_ones" => Some(BuiltinId::TensorOnes),
            "tensor_shape" => Some(BuiltinId::TensorShape),
            "tensor_reshape" => Some(BuiltinId::TensorReshape),
            "tensor_transpose" => Some(BuiltinId::TensorTranspose),
            "tensor_sum" => Some(BuiltinId::TensorSum),
            "tensor_mean" => Some(BuiltinId::TensorMean),
            "tensor_dot" => Some(BuiltinId::TensorDot),
            "predict" => Some(BuiltinId::Predict),
            "similarity" => Some(BuiltinId::Similarity),
            "ai_complete" => Some(BuiltinId::AiComplete),
            "ai_chat" => Some(BuiltinId::AiChat),
            "model_save" => Some(BuiltinId::ModelSave),
            "model_load" => Some(BuiltinId::ModelLoad),
            "model_register" => Some(BuiltinId::ModelRegister),
            "model_list" => Some(BuiltinId::ModelList),
            "model_get" => Some(BuiltinId::ModelGet),
            "alert_slack" => Some(BuiltinId::AlertSlack),
            "alert_webhook" => Some(BuiltinId::AlertWebhook),
            "emit" => Some(BuiltinId::Emit),
            "lineage" => Some(BuiltinId::Lineage),
            "run_pipeline" => Some(BuiltinId::RunPipeline),
            "sqrt" => Some(BuiltinId::Sqrt),
            "pow" => Some(BuiltinId::Pow),
            "floor" => Some(BuiltinId::Floor),
            "ceil" => Some(BuiltinId::Ceil),
            "round" => Some(BuiltinId::Round),
            "sin" => Some(BuiltinId::Sin),
            "cos" => Some(BuiltinId::Cos),
            "tan" => Some(BuiltinId::Tan),
            "log" => Some(BuiltinId::Log),
            "log2" => Some(BuiltinId::Log2),
            "log10" => Some(BuiltinId::Log10),
            "join" => Some(BuiltinId::Join),
            "http_get" => Some(BuiltinId::HttpGet),
            "http_post" => Some(BuiltinId::HttpPost),
            "assert" => Some(BuiltinId::Assert),
            "assert_eq" => Some(BuiltinId::AssertEq),
            "json_parse" => Some(BuiltinId::JsonParse),
            "json_stringify" => Some(BuiltinId::JsonStringify),
            "map_from" => Some(BuiltinId::MapFrom),
            "read_file" => Some(BuiltinId::ReadFile),
            "write_file" => Some(BuiltinId::WriteFile),
            "append_file" => Some(BuiltinId::AppendFile),
            "file_exists" => Some(BuiltinId::FileExists),
            "list_dir" => Some(BuiltinId::ListDir),
            "env_get" => Some(BuiltinId::EnvGet),
            "env_set" => Some(BuiltinId::EnvSet),
            "regex_match" => Some(BuiltinId::RegexMatch),
            "regex_find" => Some(BuiltinId::RegexFind),
            "regex_replace" => Some(BuiltinId::RegexReplace),
            "now" => Some(BuiltinId::Now),
            "date_format" => Some(BuiltinId::DateFormat),
            "date_parse" => Some(BuiltinId::DateParse),
            "zip" => Some(BuiltinId::Zip),
            "enumerate" => Some(BuiltinId::Enumerate),
            "bool" => Some(BuiltinId::Bool),
            "spawn" => Some(BuiltinId::Spawn),
            "sleep" => Some(BuiltinId::Sleep),
            "channel" => Some(BuiltinId::Channel),
            "send" => Some(BuiltinId::Send),
            "recv" => Some(BuiltinId::Recv),
            "try_recv" => Some(BuiltinId::TryRecv),
            "await_all" => Some(BuiltinId::AwaitAll),
            "pmap" => Some(BuiltinId::Pmap),
            "timeout" => Some(BuiltinId::Timeout),
            "next" => Some(BuiltinId::Next),
            "is_generator" => Some(BuiltinId::IsGenerator),
            "iter" => Some(BuiltinId::Iter),
            "take" => Some(BuiltinId::Take),
            "skip" => Some(BuiltinId::Skip_),
            "gen_collect" => Some(BuiltinId::GenCollect),
            "gen_map" => Some(BuiltinId::GenMap),
            "gen_filter" => Some(BuiltinId::GenFilter),
            "chain" => Some(BuiltinId::Chain),
            "gen_zip" => Some(BuiltinId::GenZip),
            "gen_enumerate" => Some(BuiltinId::GenEnumerate),
            _ => None,
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            BuiltinId::Print => "print",
            BuiltinId::Println => "println",
            BuiltinId::Len => "len",
            BuiltinId::Str => "str",
            BuiltinId::Int => "int",
            BuiltinId::Float => "float",
            BuiltinId::Abs => "abs",
            BuiltinId::Min => "min",
            BuiltinId::Max => "max",
            BuiltinId::Range => "range",
            BuiltinId::Push => "push",
            BuiltinId::TypeOf => "type_of",
            BuiltinId::Map => "map",
            BuiltinId::Filter => "filter",
            BuiltinId::Reduce => "reduce",
            BuiltinId::Sum => "sum",
            BuiltinId::Any => "any",
            BuiltinId::All => "all",
            BuiltinId::ReadCsv => "read_csv",
            BuiltinId::ReadParquet => "read_parquet",
            BuiltinId::WriteCsv => "write_csv",
            BuiltinId::WriteParquet => "write_parquet",
            BuiltinId::Collect => "collect",
            BuiltinId::Show => "show",
            BuiltinId::Describe => "describe",
            BuiltinId::Head => "head",
            BuiltinId::Postgres => "postgres",
            BuiltinId::Tensor => "tensor",
            BuiltinId::TensorZeros => "tensor_zeros",
            BuiltinId::TensorOnes => "tensor_ones",
            BuiltinId::TensorShape => "tensor_shape",
            BuiltinId::TensorReshape => "tensor_reshape",
            BuiltinId::TensorTranspose => "tensor_transpose",
            BuiltinId::TensorSum => "tensor_sum",
            BuiltinId::TensorMean => "tensor_mean",
            BuiltinId::TensorDot => "tensor_dot",
            BuiltinId::Predict => "predict",
            BuiltinId::Similarity => "similarity",
            BuiltinId::AiComplete => "ai_complete",
            BuiltinId::AiChat => "ai_chat",
            BuiltinId::ModelSave => "model_save",
            BuiltinId::ModelLoad => "model_load",
            BuiltinId::ModelRegister => "model_register",
            BuiltinId::ModelList => "model_list",
            BuiltinId::ModelGet => "model_get",
            BuiltinId::AlertSlack => "alert_slack",
            BuiltinId::AlertWebhook => "alert_webhook",
            BuiltinId::Emit => "emit",
            BuiltinId::Lineage => "lineage",
            BuiltinId::RunPipeline => "run_pipeline",
            BuiltinId::Sqrt => "sqrt",
            BuiltinId::Pow => "pow",
            BuiltinId::Floor => "floor",
            BuiltinId::Ceil => "ceil",
            BuiltinId::Round => "round",
            BuiltinId::Sin => "sin",
            BuiltinId::Cos => "cos",
            BuiltinId::Tan => "tan",
            BuiltinId::Log => "log",
            BuiltinId::Log2 => "log2",
            BuiltinId::Log10 => "log10",
            BuiltinId::Join => "join",
            BuiltinId::HttpGet => "http_get",
            BuiltinId::HttpPost => "http_post",
            BuiltinId::Assert => "assert",
            BuiltinId::AssertEq => "assert_eq",
            BuiltinId::JsonParse => "json_parse",
            BuiltinId::JsonStringify => "json_stringify",
            BuiltinId::MapFrom => "map_from",
            BuiltinId::ReadFile => "read_file",
            BuiltinId::WriteFile => "write_file",
            BuiltinId::AppendFile => "append_file",
            BuiltinId::FileExists => "file_exists",
            BuiltinId::ListDir => "list_dir",
            BuiltinId::EnvGet => "env_get",
            BuiltinId::EnvSet => "env_set",
            BuiltinId::RegexMatch => "regex_match",
            BuiltinId::RegexFind => "regex_find",
            BuiltinId::RegexReplace => "regex_replace",
            BuiltinId::Now => "now",
            BuiltinId::DateFormat => "date_format",
            BuiltinId::DateParse => "date_parse",
            BuiltinId::Zip => "zip",
            BuiltinId::Enumerate => "enumerate",
            BuiltinId::Bool => "bool",
            BuiltinId::Spawn => "spawn",
            BuiltinId::Sleep => "sleep",
            BuiltinId::Channel => "channel",
            BuiltinId::Send => "send",
            BuiltinId::Recv => "recv",
            BuiltinId::TryRecv => "try_recv",
            BuiltinId::AwaitAll => "await_all",
            BuiltinId::Pmap => "pmap",
            BuiltinId::Timeout => "timeout",
            BuiltinId::Next => "next",
            BuiltinId::IsGenerator => "is_generator",
            BuiltinId::Iter => "iter",
            BuiltinId::Take => "take",
            BuiltinId::Skip_ => "skip",
            BuiltinId::GenCollect => "gen_collect",
            BuiltinId::GenMap => "gen_map",
            BuiltinId::GenFilter => "gen_filter",
            BuiltinId::Chain => "chain",
            BuiltinId::GenZip => "gen_zip",
            BuiltinId::GenEnumerate => "gen_enumerate",
        }
    }
}

/// Table pipe operation descriptor, stored as a constant.
#[derive(Debug, Clone)]
pub struct TableOpDescriptor {
    pub op_name: String,
    pub args: Vec<AstExpr>,
}
